In [4]:
from torch.utils.data import Dataset, DataLoader
import torch

In [2]:
import numpy as np

In [12]:
class MyTensorDataset(Dataset):
    def __init__(self, X, y):
        # X, y are both numpy arrays, y is binary
        self.X = torch.tensor(X, dtype = torch.float32)
        self.y = torch.tensor(y, dtype = torch.long)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx, ...], self.y[idx, ...]

In [ ]:
x = np.random.rand(500, 10, 24)
y = np.random.randint(0, 2, (500))

dataset = MyTensorDataset(x, y)

In [21]:
x_sample, y_sample = dataset[0]

In [22]:
x_sample.shape

torch.Size([10, 24])

In [25]:
y_sample.item()

1

In [26]:
dataloader = DataLoader(dataset, batch_size = 32, shuffle = True)

In [ ]:
n_epoch = 100

for epoch in range(n_epoch):
    running_loss = 0
    for input, target in dataloader:
        optimizer.zero_grad()
        loss = loss_fn(model(input), target)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()

In [27]:
import pandas as pd

In [28]:
import pandas as pd

df = pd.DataFrame({
    "user_id": [1,2,3,4],
    "age": [23,45,31,19],
    "country": ["US","US","UK","US"]
})

In [31]:
df.head(2)

   user_id  age country
0        1   23      US
1        2   45      US

In [29]:
# Return users older than 25 from the US.

In [34]:
df[(df['age']>25) & (df['country']== 'US')]

   user_id  age country
1        2   45      US

In [50]:
df = pd.DataFrame({
    "user_id":[1,2,1,3,2],
    "purchase":[100,200,50,80,120],
    "other":[100,200,300,400,500]
})

In [51]:
df.head()

   user_id  purchase  other
0        1       100    100
1        2       200    200
2        1        50    300
3        3        80    400
4        2       120    500

In [52]:
# Compute total purchase per user.

In [53]:
df.groupby("user_id")["purchase"].sum()

user_id
1    150
2    320
3     80
Name: purchase, dtype: int64

In [54]:
df_per_user = df.groupby("user_id").sum()

In [55]:
df_per_user

         purchase  other
user_id
1             150    400
2             320    700
3              80    400

In [ ]:
# Sort users by other amount descending.

In [60]:
df_per_user.sort_values(["other", "purchase"], ascending=False)

         purchase  other
user_id
2             320    700
1             150    400
3              80    400

In [44]:
df = pd.DataFrame({
    "user_id":[1,1,1,2,2,3],
    "product":["A","B","A","A","C","B"]
})

In [45]:
# Find number of unique products each user bought.

In [46]:
df.groupby("user_id")["product"].nunique()

user_id
1    2
2    2
3    1
Name: product, dtype: int64

In [47]:
df.groupby("user_id").nunique()

         product
user_id
1              2
2              2
3              1

In [65]:
df = pd.DataFrame({
    "user":[1,2,3,4],
    "age":[25,None,30,None]
})

In [66]:
df.head()

   user   age
0     1  25.0
1     2   NaN
2     3  30.0
3     4   NaN

In [63]:
df['age'].fillna(df['age'].median(), inplace=True)

/var/folders/vd/69kmbq6s0s331vf09zfxgmh40000gn/T/ipykernel_65700/1654433547.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)

In [64]:
df.head()

   user   age
0     1  25.0
1     2  27.5
2     3  30.0
3     4  27.5

In [67]:
df = pd.DataFrame({
    "price":[10,20,30],
    "quantity":[1,3,2]
})

In [68]:
# Create a column total = price * quantity

In [69]:
df["total"] = df["price"] * df["quantity"]

In [70]:
users = pd.DataFrame({
    "user_id":[1,2,3],
    "country":["US","UK","US"]
})

In [71]:
orders = pd.DataFrame({
    "user_id":[1,1,2],
    "amount":[100,50,80]
})

In [72]:
pd.merge(users, orders, on="user_id", how="left")

   user_id country  amount
0        1      US   100.0
1        1      US    50.0
2        2      UK    80.0
3        3      US     NaN