In [1]:
import pandas as pd
import numpy as np

In [4]:
RequestAccepted = pd.DataFrame({
    "requester_id": [1, 1, 2, 3],
    "accepter_id": [2, 3, 3, 4],
    "accept_date": ["2016/06/03", "2016/06/08", "2016/06/08", "2016/06/09"]
})

In [22]:
req_count = RequestAccepted.groupby('requester_id')[['accepter_id']].count().rename(columns={'accepter_id':'req_count'}).reset_index()

In [23]:
req_count

   requester_id  req_count
0             1          2
1             2          1
2             3          1

In [20]:
acp_count = RequestAccepted.groupby('accepter_id')[['requester_id']].count().rename(columns={'requester_id':'acp_count'}).reset_index()

In [21]:
acp_count

   accepter_id  acp_count
0            2          1
1            3          2
2            4          1

In [35]:
merged = req_count.merge(acp_count, left_on='requester_id', right_on='accepter_id', how='outer')

In [45]:
merged.fillna(0, inplace=True)

In [46]:
merged['total_count'] = merged['req_count'] + merged['acp_count']

In [47]:
merged

   requester_id  req_count  accepter_id  acp_count  total_count
0           1.0        2.0          0.0        0.0          2.0
1           2.0        1.0          2.0        1.0          2.0
2           3.0        1.0          3.0        2.0          3.0
3           0.0        0.0          4.0        1.0          1.0

In [49]:
row = merged[merged['total_count'] == merged.total_count.max()]

In [57]:
row.reset_index(inplace=True)

In [60]:
id = row.loc[0, 'requester_id'] or row.loc[0, 'accpeter_id']

In [61]:
count = row.loc[0, 'total_count']

In [62]:
pd.DataFrame({'id':[id], 'num':[count]})

    id  num
0  3.0  3.0

In [63]:
tree = pd.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "p_id": [np.nan, 1, 1, 2, 2]
})

In [66]:
tree.merge(tree, left_on='id', right_on='p_id', how='left')

   id_x  p_id_x  id_y  p_id_y
0     1     NaN   2.0     1.0
1     1     NaN   3.0     1.0
2     2     1.0   4.0     2.0
3     2     1.0   5.0     2.0
4     3     1.0   NaN     NaN
5     4     2.0   NaN     NaN
6     5     2.0   NaN     NaN