In [3]:
import pandas as pd
import numpy as np

In [8]:
series = pd.Series(np.arange(5), index=np.arange(5))

In [9]:
series

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [12]:
series[series > 2]

3    3
4    4
dtype: int64

In [13]:
s2 = pd.Series({'a':1, 'b':2, 'c':3})

In [17]:
s2[s2.index == 'c']

c    3
dtype: int64

In [22]:
s3 = pd.Series({'a':5, 'b':3, 'c':4, 'd':8})

In [24]:
s4 = s2 + s3

In [28]:
s4[s4.notna()]

a    6.0
b    5.0
c    7.0
dtype: float64

In [35]:
s4.bfill()

a    6.0
b    5.0
c    7.0
d    NaN
dtype: float64

In [38]:
s4.fillna(s4.median())

a    6.0
b    5.0
c    7.0
d    6.0
dtype: float64

In [39]:
data = [['xiaoming', 10], ['xiaohong', 11], ['xiaozhang', 12]]
df = pd.DataFrame(data, columns=['Name', 'Age'])

In [41]:
df

        Name  Age
0   xiaoming   10
1   xiaohong   11
2  xiaozhang   12

In [42]:
data = {'Name': ['xiaoming', 'zhangsan', 'lisi'], 'Age':[10, 11, 21]}
df = pd.DataFrame(data)

In [44]:
df.ndim

2

In [45]:
df2 = pd.DataFrame({'A' : 1.,
                          'B' : pd.Timestamp('20130102'),
                          'C' : pd.Series(1,index=list(range(4)), dtype='float32'),
                          'D' : np.array([3] * 4, dtype='int32'),
                          'E' : pd.Categorical(["test","train","test","train"]),
                          'F' : 'foo' })

In [50]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [51]:
df = pd.DataFrame(np.random.randn(6,4), index=list("abcdef"), columns=list('ABCD'))

In [52]:
df

          A         B         C         D
a -0.216546  1.579700 -0.700174 -0.222082
b  0.165580 -0.872704 -1.331973  1.606470
c -1.208402 -0.231980  1.176157 -0.774773
d  0.514961 -2.009199  1.829624 -0.156438
e -0.198661 -0.190720 -0.107228 -0.689609
f -0.489481 -1.262066 -0.220144  0.935500

In [55]:
df2 = pd.DataFrame(np.arange(12).reshape(3, 4), index=list("abc"),columns=list("WXYZ"))

In [56]:
df2

   W  X   Y   Z
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [74]:
df.loc[['a', 'b']]

          A         B         C         D
a -0.216546  1.579700 -0.700174 -0.222082
b  0.165580 -0.872704 -1.331973  1.606470

In [77]:
df.loc[:, ['A', 'B']]

          A         B
a -0.216546  1.579700
b  0.165580 -0.872704
c -1.208402 -0.231980
d  0.514961 -2.009199
e -0.198661 -0.190720
f -0.489481 -1.262066

In [80]:
df.iloc[1:3,2:3]

          C
b -1.331973
c  1.176157

In [81]:
df.iloc[1,2] = 5

In [84]:
df1 = pd.DataFrame({'key':['s','s','w','x','x','n','f','c'], 'data1':range(8)})
df2 = pd.DataFrame({'key':['w','w','s','s','x','f'], 'data2':range(6)})

In [88]:
df1

  key  data1
0   s      0
1   s      1
2   w      2
3   x      3
4   x      4
5   n      5
6   f      6
7   c      7

In [86]:
df2

  key  data2
0   w      0
1   w      1
2   s      2
3   s      3
4   x      4
5   f      5

In [90]:
pd.merge(df1, df2, how='inner')

  key  data1  data2
0   s      0      2
1   s      0      3
2   s      1      2
3   s      1      3
4   w      2      0
5   w      2      1
6   x      3      4
7   x      4      4
8   f      6      5

In [93]:
data = {"lessons": ['Ch', 'En', 'Ch', 'En', 'Ch', 'Ma', 'En', 'Ma'],
         	  "grade": ['A', 'A', 'B', 'B', 'C', 'A', 'C', 'B'],
        	  "male": np.random.randint(10, 20, 8),  # [10, 20)的8个随机整数
       	 	  "female": np.random.randint(10, 20, 8)}
df = pd.DataFrame(data)

In [94]:
df

  lessons grade  male  female
0      Ch     A    11      11
1      En     A    14      18
2      Ch     B    11      15
3      En     B    13      17
4      Ch     C    10      18
5      Ma     A    18      12
6      En     C    17      12
7      Ma     B    14      17

In [105]:
df_g = df.groupby(by='grade').count()

In [106]:
df_g

       lessons  male  female
grade
A            3     3       3
B            3     3       3
C            2     2       2

In [113]:
for i in range(len(df_g.index)):
    print(df_g.iloc[i, 0])

3
3
2

In [115]:
df.groupby(by=['lessons', 'grade']).sum()

               male  female
lessons grade
Ch      A        11      11
        B        11      15
        C        10      18
En      A        14      18
        B        13      17
        C        17      12
Ma      A        18      12
        B        14      17

In [133]:
df = pd.DataFrame(np.random.randn(4, 5), index=["one", "two", "three", "four"], columns=list("ABCDE"))
df.iloc[0, 2] = np.nan
df.iloc[[1, 3], 4] = np.nan

In [134]:
df

              A         B         C         D         E
one   -0.624356 -0.342132       NaN  0.383104  1.036179
two    1.204911 -0.981820  1.270802 -1.500317       NaN
three -0.323858 -0.383079 -0.325178 -1.337929  1.513778
four  -2.271796  0.032074  0.437684  0.137697       NaN

In [136]:
df.fillna(value=df.mean(), inplace=True)

In [142]:
for col in df.columns:
    df[col+'cum_sum'] = df[col].cumsum()

In [143]:
df

,A,B,C,D,E,Acum_sum,Bcum_sum,Ccum_sum,Dcum_sum,Ecum_sum
one,-0.624356,-0.342132,0.461103,0.383104,1.036179,-0.624356,-0.342132,0.461103,0.383104,1.036179
two,1.204911,-0.981820,1.270802,-1.500317,1.274979,0.580555,-1.323952,1.731904,-1.117213,2.311158
three,-0.323858,-0.383079,-0.325178,-1.337929,1.513778,0.256697,-1.707031,1.406727,-2.455141,3.824937
four,-2.271796,0.032074,0.437684,0.137697,1.274979,-2.015099,-1.674957,1.844410,-2.317444,5.099916

In [120]:
df = pd.DataFrame({
    'id': ['a', 'b', 'c'],
    'A': [10, 20, 30]
})

In [121]:
df

  id   A
0  a  10
1  b  20
2  c  30

In [124]:
df.set_index('id', inplace=True)

In [126]:
df

     A
id
a   10
b   20
c   30

In [125]:
df.index

Index(['a', 'b', 'c'], dtype='object', name='id')

In [148]:
df = pd.DataFrame({'id':[1,2,3, 4], 'salary':[100,200,300, 300]})

In [151]:
df2 = df.groupby('salary').count().sort_values(by='salary', ascending=False)

In [152]:
df2

        id
salary
300      2
200      1
100      1

In [154]:
for i in range(len(df2.index)):
    if df2.iloc[i, 0] == 1:
        print( df2.index[i])
        break

200

In [158]:
df2.iloc[1].loc['id'] = 10

/var/folders/vd/69kmbq6s0s331vf09zfxgmh40000gn/T/ipykernel_97146/2676649961.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2.iloc[1].loc['id'] = 10

In [159]:
# | id | name  | salary | departmentId |
# | -- | ----- | ------ | ------------ |
# | 1  | Joe   | 70000  | 1            |
# | 2  | Jim   | 90000  | 1            |
# | 3  | Henry | 80000  | 2            |
# | 4  | Sam   | 60000  | 2            |
# | 5  | Max   | 90000  | 1            |
employee = pd.DataFrame({
    'id': [1, 2, 3, 4, 5],
    'name': ['Joe', 'Jim', 'Henry', 'Sam', 'Max'],
    'salary': [70000, 90000, 80000, 60000, 90000],
    'departmentId': [1, 1, 2, 2, 1]
})

departments = pd.DataFrame({
    'id': [1, 2],
    'name': ['IT', 'Sales']
})

In [181]:
merge = employee.merge(departments, left_on='departmentId', right_on='id', how='left')

In [184]:
merge

   id_x name_x  salary  departmentId  id_y name_y
0     1    Joe   70000             1     1     IT
1     2    Jim   90000             1     1     IT
2     3  Henry   80000             2     2  Sales
3     4    Sam   60000             2     2  Sales
4     5    Max   90000             1     1     IT

In [185]:
df = merge[merge.salary == merge.groupby(by='departmentId')['salary'].transform('max')]

In [189]:
res = df[['name_y', 'name_x', 'salary']].rename(columns={'name_x':'Employee', 'salary':'Salary', 'name_y': 'Department'})

In [190]:
res

  Department Employee  Salary
1         IT      Jim   90000
2      Sales    Henry   80000
4         IT      Max   90000

In [191]:
employee = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'name': ['Joe', 'Henry', 'Sam', 'Max'],
    'salary': [70000, 80000, 60000, 90000],
    'managerId': [3, 4, np.nan, np.nan]  # null → np.nan
})

In [196]:
merge = employee.merge(employee[['id', 'salary']], left_on='managerId', right_on='id', how='left')

In [204]:
merge.loc[merge['salary_x'] > merge['salary_y']][['name']].rename(columns={'name':'Employee'})

  Employee
0      Joe

In [205]:
person = pd.DataFrame({
    'id': [1, 2, 3],
    'email': ['a@b.com', 'c@d.com', 'a@b.com']
})

In [206]:
person

   id    email
0   1  a@b.com
1   2  c@d.com
2   3  a@b.com

In [212]:
counted = person.groupby(by='email')[['id']].count()

In [218]:
counted[counted['id']>=2].reset_index()[['email']].rename(columns={'email':'Email'})

     Email
0  a@b.com

In [219]:
customers = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'name': ['Joe', 'Henry', 'Sam', 'Max']
})
orders = pd.DataFrame({
    'id': [1, 2],
    'customerId': [3, 1]
})

In [220]:
customers

   id   name
0   1    Joe
1   2  Henry
2   3    Sam
3   4    Max

In [224]:
counts = orders.groupby('customerId').count().reset_index()

In [226]:
counts

   customerId  id
0           1   1
1           3   1

In [228]:
merged = customers.merge(counts, left_on='id', right_on='customerId', how='left')

In [229]:
merged

   id_x   name  customerId  id_y
0     1    Joe         1.0   1.0
1     2  Henry         NaN   NaN
2     3    Sam         3.0   1.0
3     4    Max         NaN   NaN

In [231]:
merged[merged['id_y'].isna()][['name']]

    name
1  Henry
3    Max

In [232]:
weather = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'recordDate': pd.to_datetime([
        '2015-01-01',
        '2015-01-02',
        '2015-01-03',
        '2015-01-04'
    ]),
    'temperature': [10, 25, 20, 30]
})

In [233]:
weather

   id recordDate  temperature
0   1 2015-01-01           10
1   2 2015-01-02           25
2   3 2015-01-03           20
3   4 2015-01-04           30

In [234]:
weather['last_temp'] = weather['temperature'].shift(1)

In [237]:
weather[weather['temperature'] > weather['last_temp']][['id']]

   id
1   2
3   4

In [242]:
weather.temperature.diff()

0     NaN
1    15.0
2    -5.0
3    10.0
Name: temperature, dtype: float64

In [245]:
weather.recordDate.diff().dt.days

0    NaN
1    0.0
2    0.0
3    0.0
Name: recordDate, dtype: float64

In [254]:
activity = pd.DataFrame({
    'player_id': [1, 1, 2, 3, 3],
    'device_id': [2, 2, 3, 1, 4],
    'event_date': pd.to_datetime([
        '2016-03-01',
        '2016-05-02',
        '2017-06-25',
        '2016-03-02',
        '2018-07-03'
    ]),
    'games_played': [5, 6, 1, 0, 5]
})

In [255]:
activity

   player_id  device_id event_date  games_played
0          1          2 2016-03-01             5
1          1          2 2016-05-02             6
2          2          3 2017-06-25             1
3          3          1 2016-03-02             0
4          3          4 2018-07-03             5

In [253]:
activity.groupby('player_id')[['event_date']].min().reset_index().rename(columns={'event_date':'first_login'})

   player_id first_login
0          1  2016-03-01
1          2  2017-06-25
2          3  2016-03-02

In [270]:
activity = pd.DataFrame({
    'player_id': [1, 1, 2, 3, 3],
    'device_id': [2, 2, 3, 1, 4],
    'event_date': pd.to_datetime([
        '2016-03-01',
        '2016-03-02',
        '2017-06-25',
        '2016-03-02',
        '2018-07-03'
    ]),
    'games_played': [5, 6, 1, 0, 5]
})

In [271]:
activity.sort_values(['player_id', 'event_date'], inplace=True)

In [275]:
activity['first_login'] = activity.groupby('player_id')['event_date'].transform('min')

In [278]:
n_player = len(activity[(activity['event_date'] - activity['first_login']).dt.days == 1])

1

In [281]:
total_players= len(activity['player_id'].drop_duplicates())

In [342]:
trips = pd.DataFrame({
    'id': [1,2,3,4,5,6,7,8,9,10, 11],
    'client_id': [1,2,3,4,1,2,3,2,3,4, 4],
    'driver_id': [10,11,12,13,10,11,12,12,10,13, 13],
    'city_id': [1,1,6,6,1,6,6,12,12,12, 12],
    'status': [
        'completed',
        'cancelled_by_driver',
        'completed',
        'cancelled_by_client',
        'completed',
        'completed',
        'completed',
        'completed',
        'completed',
        'cancelled_by_driver',
        'cancelled_by_driver',
    ],
    'request_at': pd.to_datetime([
        '2013-10-01',
        '2013-10-01',
        '2013-10-01',
        '2013-10-01',
        '2013-10-02',
        '2013-10-02',
        '2013-10-02',
        '2013-10-03',
        '2013-10-03',
        '2013-10-03',
        '2013-10-04',
    ])
})

users = pd.DataFrame({
    'users_id': [1, 2, 3, 4, 10, 11, 12, 13],
    'banned': ['No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No'],
    'role': ['client', 'client', 'client', 'client', 'driver', 'driver', 'driver', 'driver']
})

In [343]:
trips

    id  client_id  driver_id  city_id               status request_at
0    1          1         10        1            completed 2013-10-01
1    2          2         11        1  cancelled_by_driver 2013-10-01
2    3          3         12        6            completed 2013-10-01
3    4          4         13        6  cancelled_by_client 2013-10-01
4    5          1         10        1            completed 2013-10-02
5    6          2         11        6            completed 2013-10-02
6    7          3         12        6            completed 2013-10-02
7    8          2         12       12            completed 2013-10-03
8    9          3         10       12            completed 2013-10-03
9   10          4         13       12  cancelled_by_driver 2013-10-03
10  11          4         13       12  cancelled_by_driver 2013-10-04

In [344]:
users

   users_id banned    role
0         1     No  client
1         2    Yes  client
2         3     No  client
3         4     No  client
4        10     No  driver
5        11     No  driver
6        12     No  driver
7        13     No  driver

In [345]:
clients = users[users['role'] == 'client']

In [346]:
drivers = users[users['role'] == 'driver']

In [347]:
drivers

   users_id banned    role
4        10     No  driver
5        11     No  driver
6        12     No  driver
7        13     No  driver

In [348]:
merge1 = trips.merge(clients[['users_id', 'banned']], left_on='client_id', right_on='users_id')\
            .rename(columns={'banned': 'client_banned'}).drop('users_id', axis=1)

In [349]:
merge2 = merge1.merge(drivers[['users_id', 'banned']], left_on='driver_id', right_on='users_id')\
            .rename(columns={'banned':'driver_banned'}).drop('users_id', axis=1)

In [350]:
merge2

,id,client_id,driver_id,city_id,status,request_at,client_banned,driver_banned
0,1,1,10,1,completed,2013-10-01,No,No
1,2,2,11,1,cancelled_by_driver,2013-10-01,Yes,No
2,3,3,12,6,completed,2013-10-01,No,No
3,4,4,13,6,cancelled_by_client,2013-10-01,No,No
4,5,1,10,1,completed,2013-10-02,No,No
5,6,2,11,6,completed,2013-10-02,Yes,No
6,7,3,12,6,completed,2013-10-02,No,No
7,8,2,12,12,completed,2013-10-03,Yes,No
8,9,3,10,12,completed,2013-10-03,No,No
9,10,4,13,12,cancelled_by_driver,2013-10-03,No,No
10,11,4,13,12,cancelled_by_driver,2013-10-04,No,No

In [353]:
valid_trip = merge2[(merge2['client_banned'] == 'No') & (merge2['driver_banned'] == 'No') & (merge2['request_at'].between('2013-10-01', '2013-10-03'))]

In [354]:
valid_trip

,id,client_id,driver_id,city_id,status,request_at,client_banned,driver_banned
0,1,1,10,1,completed,2013-10-01,No,No
2,3,3,12,6,completed,2013-10-01,No,No
3,4,4,13,6,cancelled_by_client,2013-10-01,No,No
4,5,1,10,1,completed,2013-10-02,No,No
6,7,3,12,6,completed,2013-10-02,No,No
8,9,3,10,12,completed,2013-10-03,No,No
9,10,4,13,12,cancelled_by_driver,2013-10-03,No,No

In [323]:
total_trips = valid_trip.groupby('request_at')['id'].count().reset_index()

In [324]:
total_trips

  request_at  id
0 2013-10-01   3
1 2013-10-02   2
2 2013-10-03   2

In [334]:
cancel_count = valid_trip.groupby('request_at')['status'].apply(lambda x: ((x=='cancelled_by_client') | (x=='cancelled_by_driver')).sum()).reset_index()

In [335]:
cancel_count

  request_at  status
0 2013-10-01       1
1 2013-10-02       0
2 2013-10-03       1

In [325]:
merge3 = total_trips.merge(cancel_count, on='request_at', how='inner')

In [326]:
merge3

  request_at  id  status
0 2013-10-01   3       1
1 2013-10-02   2       0
2 2013-10-03   2       0

In [336]:
merge3['Cancellation Rate'] = merge3.apply(lambda x: np.round(x['status'] / x['id'], 2) if x['id'] - x['status'] != 0 else np.nan, axis=1)

In [339]:
merge3.rename(columns={'request_at': 'Day'})[['Day', 'Cancellation Rate']].dropna(subset=['Cancellation Rate'])

         Day  Cancellation Rate
0 2013-10-01               0.33
1 2013-10-02               0.00
2 2013-10-03               0.00

In [355]:
employee = pd.DataFrame({
    'id': [101, 102, 103, 104, 105, 106],
    'name': ['John', 'Dan', 'James', 'Amy', 'Anne', 'Ron'],
    'department': ['A', 'A', 'A', 'A', 'A', 'B'],
    'managerId': [np.nan, 101, 101, 101, 101, 101]
})

In [356]:
employee

    id   name department  managerId
0  101   John          A        NaN
1  102    Dan          A      101.0
2  103  James          A      101.0
3  104    Amy          A      101.0
4  105   Anne          A      101.0
5  106    Ron          B      101.0

In [374]:
reports = employee.groupby('managerId')[['id']].count()

In [375]:
reports

           id
managerId
101.0       5

In [380]:
reports = employee.groupby('managerId')[['id']].count().reset_index().rename(columns={'id': 'reports'})

In [381]:
reports

   managerId  reports
0      101.0        5

In [382]:
merged = employee.merge(reports, left_on='id', right_on='managerId', how = 'left')

In [383]:
merged[merged['reports'] >=5][['name']]

   name
0   NaN

In [384]:
employee = pd.DataFrame({
    'id': [101, 102, 103, 104, 105, 106],
    'name': [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan],
    'department': ['A', 'A', 'A', 'A', 'A', 'B'],
    'managerId': [np.nan, 101, 101, 101, 101, 101]
})

In [385]:
reports = employee.groupby('managerId')[['id']].count().reset_index().rename(columns={'id': 'reports'})
merged = employee.merge(reports, left_on='id', right_on='managerId', how = 'left')
merged[merged['reports'] >=5][['name']]

   name
0   NaN

In [372]:
merged

    id  name department  managerId_x  managerId_y  reports
0  101   NaN          A          NaN        101.0      0.0
1  102   NaN          A        101.0          NaN      NaN
2  103   NaN          A        101.0          NaN      NaN
3  104   NaN          A        101.0          NaN      NaN
4  105   NaN          A        101.0          NaN      NaN
5  106   NaN          B        101.0          NaN      NaN

In [386]:
employee = pd.DataFrame({
    'empId': [3, 1, 2, 4],
    'name': ['Brad', 'John', 'Dan', 'Thomas'],
    'supervisor': [np.nan, 3, 3, 3],
    'salary': [4000, 1000, 2000, 4000]
})

In [387]:
bonus = pd.DataFrame({
    'empId': [2, 4],
    'bonus': [500, 2000]
})

In [392]:
merged = employee.merge(bonus, on='empId', how='left')

In [395]:
merged

   empId    name  supervisor  salary   bonus
0      3    Brad         NaN    4000     NaN
1      1    John         3.0    1000     NaN
2      2     Dan         3.0    2000   500.0
3      4  Thomas         3.0    4000  2000.0

In [396]:
merged[(merged['bonus'] < 1000) | merged['bonus'].isna()][['name', 'bonus']]

   name  bonus
0  Brad    NaN
1  John    NaN
2   Dan  500.0

In [403]:
insurance = pd.DataFrame({
    'pid': [1, 2, 3, 4],
    'tiv_2015': [10, 20, 10, 10],
    'tiv_2016': [5, 20, 30, 40],
    'lat': [10, 20, 20, 40],
    'lon': [10, 20, 20, 40]
})

In [407]:
insurance.duplicated('tiv_2015', keep=False)

0     True
1    False
2     True
3     True
dtype: bool

In [410]:
~insurance.duplicated(['lat', 'lon'], keep=False)

0     True
1    False
2    False
3     True
dtype: bool

In [412]:
filtered = insurance[(insurance.duplicated('tiv_2015', keep=False)) & (~insurance.duplicated(['lat', 'lon'], keep=False))]

In [413]:
filtered['tiv_2016'].sum()

45

In [415]:
pd.DataFrame({'tiv_2016': [round(filtered['tiv_2016'].sum(), 2)]})

   tiv_2016
0        45