In [1]:
import pandas as pd

In [78]:
import numpy as np

In [2]:
data = [[1, 1], [2, 2], [3, 3], [4, 3]]
orders = pd.DataFrame(data, columns=['order_number', 'customer_number']).astype({'order_number':'Int64', 'customer_number':'Int64'})

In [3]:
orders

   order_number  customer_number
0             1                1
1             2                2
2             3                3
3             4                3

In [14]:
res = orders.groupby('customer_number')['order_number'].count().reset_index().sort_values('order_number', ascending=False)

In [17]:
customer = res.loc[res.index[0], 'customer_number']

In [18]:
pd.DataFrame({'customer_number':[customer]})

   customer_number
0                3

In [38]:
data = [[1, 100], [2, 200], [3, 300]]
employee = pd.DataFrame(data, columns=['Id', 'Salary']).astype({'Id':'Int64', 'Salary':'Int64'})

In [42]:
res = employee.groupby('Salary').count().reset_index().sort_values('Salary', ascending=False)

In [35]:
n = 2
if len(res) < n:
    result = pd.DataFrame({f'getNthHighestSalary({n})': [np.nan]})
else:
    salary = res.loc[res.index[n-1], 'Salary']
    result = pd.DataFrame({f'getNthHighestSalary({n})': [salary]})

In [36]:
result

   getNthHighestSalary(2)
0                     200

In [48]:
data = [[1, 3.5], [2, 3.65], [3, 4.0], [4, 3.85], [5, 4.0], [6, 3.65]]
scores = pd.DataFrame(data, columns=['id', 'score']).astype({'id':'Int64', 'score':'Float64'})

In [50]:
scores['rank'] = scores['score'].rank(method='dense', ascending=False)

In [53]:
scores.sort_values('rank').drop('id', axis=1)

   score  rank
2    4.0   1.0
4    4.0   1.0
3   3.85   2.0
1   3.65   3.0
5   3.65   3.0
0    3.5   4.0

In [74]:
data = [[1, 1], [2, 1], [3, 1], [4, 2], [5, 1], [6, 2], [7, 2]]
logs = pd.DataFrame(data, columns=['id', 'num']).astype({'id':'Int64', 'num':'Int64'})

In [60]:
logs['prev1'] = logs['num'].shift(1)
logs['prev2'] = logs['num'].shift(2)

In [65]:
res = logs[(logs['prev1'] == logs['num']) & (logs['prev2'] == logs['num'])]

In [67]:
pd.DataFrame({'ConsecutiveNums': res['num']})

   ConsecutiveNums
2                1

In [75]:
logs['unique'] = logs['num'].rolling(3).apply(lambda x: x.nunique())

In [77]:
logs[logs['unique'] == 1]

   id  num  unique
2   3    1     1.0

In [86]:
data = [[1, 10, 5, 10, 10], [2, 20, 20, 20, 20], [3, 10, 30, 20, 20], [4, 10, 40, 40, 40]]
insurance = pd.DataFrame(data, columns=['pid', 'tiv_2015', 'tiv_2016', 'lat', 'lon']).astype({'pid':'Int64', 'tiv_2015':'Float64', 'tiv_2016':'Float64', 'lat':'Float64', 'lon':'Float64'})

In [89]:
insurance['tiv_count'] = insurance.groupby('tiv_2015')['pid'].transform('count')

In [91]:
insurance['loc_count'] = insurance.groupby(['lat', 'lon'])['pid'].transform('count')

In [95]:
res = insurance[(insurance['tiv_count'] > 1)&(insurance['loc_count']==1)]['tiv_2016'].sum()

In [96]:
pd.DataFrame({'tiv_2016':[res]})

   tiv_2016
0      45.0

In [97]:
data = [[1, 'Joe', 85000, 1], [2, 'Henry', 80000, 2], [3, 'Sam', 60000, 2], [4, 'Max', 90000, 1], [5, 'Janet', 69000, 1], [6, 'Randy', 85000, 1], [7, 'Will', 70000, 1]]
employee = pd.DataFrame(data, columns=['id', 'name', 'salary', 'departmentId']).astype({'id':'Int64', 'name':'object', 'salary':'Int64', 'departmentId':'Int64'})
data = [[1, 'IT'], [2, 'Sales']]
department = pd.DataFrame(data, columns=['id', 'name']).astype({'id':'Int64', 'name':'object'})

In [103]:
employee['rank'] = employee.groupby('departmentId')['salary'].rank(method='dense', ascending=False)

In [110]:
employee[employee['rank'] <= 3].drop(['id'], axis=1).rename(columns={'name':'Employee'}).merge(department, left_on='departmentId', right_on='id', how='left')\
    .rename(columns={'name':'Department'}).drop(['departmentId', 'rank', 'id'], axis=1)

  Employee  salary Department
0      Joe   85000         IT
1    Henry   80000      Sales
2      Sam   60000      Sales
3      Max   90000         IT
4    Randy   85000         IT
5     Will   70000         IT

In [111]:
data = [['1', '1', '10', '1', 'completed', '2013-10-01'], ['2', '2', '11', '1', 'cancelled_by_driver', '2013-10-01'], ['3', '3', '12', '6', 'completed', '2013-10-01'], ['4', '4', '13', '6', 'cancelled_by_client', '2013-10-01'], ['5', '1', '10', '1', 'completed', '2013-10-02'], ['6', '2', '11', '6', 'completed', '2013-10-02'], ['7', '3', '12', '6', 'completed', '2013-10-02'], ['8', '2', '12', '12', 'completed', '2013-10-03'], ['9', '3', '10', '12', 'completed', '2013-10-03'], ['10', '4', '13', '12', 'cancelled_by_driver', '2013-10-03']]
trips = pd.DataFrame(data, columns=['id', 'client_id', 'driver_id', 'city_id', 'status', 'request_at']).astype({'id':'Int64', 'client_id':'Int64', 'driver_id':'Int64', 'city_id':'Int64', 'status':'object', 'request_at':'object'})

data = [['1', 'No', 'client'], ['2', 'Yes', 'client'], ['3', 'No', 'client'], ['4', 'No', 'client'], ['10', 'No', 'driver'], ['11', 'No', 'driver'], ['12', 'No', 'driver'], ['13', 'No', 'driver']]
users = pd.DataFrame(data, columns=['users_id', 'banned', 'role']).astype({'users_id':'Int64', 'banned':'object', 'role':'object'})

In [112]:
trips

   id  client_id  driver_id  city_id               status  request_at
0   1          1         10        1            completed  2013-10-01
1   2          2         11        1  cancelled_by_driver  2013-10-01
2   3          3         12        6            completed  2013-10-01
3   4          4         13        6  cancelled_by_client  2013-10-01
4   5          1         10        1            completed  2013-10-02
5   6          2         11        6            completed  2013-10-02
6   7          3         12        6            completed  2013-10-02
7   8          2         12       12            completed  2013-10-03
8   9          3         10       12            completed  2013-10-03
9  10          4         13       12  cancelled_by_driver  2013-10-03

In [117]:
]

   users_id banned    role
0         1     No  client
1         2    Yes  client
2         3     No  client
3         4     No  client
4        10     No  driver
5        11     No  driver
6        12     No  driver
7        13     No  driver

In [123]:
tmp = trips.merge(users[users.role=='client'].drop('role', axis=1), 
            left_on='client_id', right_on='users_id', how='left')\
    .rename(columns={'banned':'client_banned'})\
    .merge(users[users.role=='driver'].drop('role', axis=1),
          left_on='driver_id', right_on='users_id', how='left')\
    .rename(columns={'banned':'driver_banned'})

In [124]:
tmp

,id,client_id,driver_id,city_id,status,request_at,users_id_x,client_banned,users_id_y,driver_banned
0,1,1,10,1,completed,2013-10-01,1,No,10,No
1,2,2,11,1,cancelled_by_driver,2013-10-01,2,Yes,11,No
2,3,3,12,6,completed,2013-10-01,3,No,12,No
3,4,4,13,6,cancelled_by_client,2013-10-01,4,No,13,No
4,5,1,10,1,completed,2013-10-02,1,No,10,No
5,6,2,11,6,completed,2013-10-02,2,Yes,11,No
6,7,3,12,6,completed,2013-10-02,3,No,12,No
7,8,2,12,12,completed,2013-10-03,2,Yes,12,No
8,9,3,10,12,completed,2013-10-03,3,No,10,No
9,10,4,13,12,cancelled_by_driver,2013-10-03,4,No,13,No

In [128]:
tmp2 = tmp[(tmp.client_banned=='No') & (tmp.driver_banned =='No')]

In [129]:
tmp3 = tmp2[tmp2.request_at.between('2013-10-01', '2013-10-03')]

In [134]:
def count_cancelled(x):
    count = 0
    for i in x:
        if i.startswith('cancelled'):
            count +=1
    return count
res = tmp3.groupby('request_at').agg(
    total_count = ('id', 'count'),
    cancelled_count=('status', count_cancelled)
).reset_index()

In [137]:
res = res[res.total_count > 0]

In [138]:
res['Cancellation Rate'] = (res.cancelled_count / res.total_count).round(2)

In [141]:
res[['request_at', 'Cancellation Rate']].rename(columns={'request_at': 'Day'})

          Day  Cancellation Rate
0  2013-10-01               0.33
1  2013-10-02                0.0
2  2013-10-03                0.5

In [142]:
data = [[1, '192.168.1.1', 200], [2, '256.1.2.3', 404], [3, '192.168.001.1', 200], [4, '192.168.1.1', 200], [5, '192.168.1', 500], [6, '256.1.2.3', 404], [7, '192.168.001.1', 200]]
logs = pd.DataFrame(data, columns=["log_id", "ip", "status_code"]).astype({"log_id": "Int64", "ip": "string", "status_code": "Int64"})

In [143]:
logs

   log_id             ip  status_code
0       1    192.168.1.1          200
1       2      256.1.2.3          404
2       3  192.168.001.1          200
3       4    192.168.1.1          200
4       5      192.168.1          500
5       6      256.1.2.3          404
6       7  192.168.001.1          200

In [150]:
def valid_ip(x):
    octets = x.split('.')
    if len(octets) != 4:
        return False
    for o in octets:
        if o.startswith('0'):
            return False
        if int(o) > 255:
            return False
    return True
        
logs['valid'] = logs['ip'].apply(valid_ip)

In [153]:
logs[logs.valid==False].groupby('ip')['log_id'].count()\
    .reset_index().rename(columns={'log_id': 'invalid_count'})\
    .sort_values(['invalid_count', 'ip'], ascending=False)

              ip  invalid_count
2      256.1.2.3              2
0  192.168.001.1              2
1      192.168.1              1

In [154]:
data = [[1, 101, 2], [1, 102, 1], [1, 201, 3], [1, 301, 1], [2, 101, 1], [2, 102, 2], [2, 103, 1], [2, 201, 5], [3, 101, 2], [3, 103, 1], [3, 301, 4], [3, 401, 2], [4, 101, 1], [4, 201, 3], [4, 301, 1], [4, 401, 2], [5, 102, 2], [5, 103, 1], [5, 201, 2], [5, 202, 3]]
product_purchases = pd.DataFrame(data, columns={
    "user_id": pd.Series(dtype='int64'),
    "product_id": pd.Series(dtype='int64'),
    "quantity": pd.Series(dtype='int64')
})
data = [[101, 'Electronics', 100], [102, 'Books', 20], [103, 'Books', 35], [201, 'Clothing', 45], [202, 'Clothing', 60], [301, 'Sports', 75], [401, 'Kitchen', 50]]
product_info= pd.DataFrame(data, columns={
    "product_id": pd.Series(dtype='int64'),
    "category": pd.Series(dtype='string'),
    "price": pd.Series(dtype='float64')  # Reflects NUMBER(10, 2)
})

In [156]:
product_info

   product_id     category  price
0         101  Electronics    100
1         102        Books     20
2         103        Books     35
3         201     Clothing     45
4         202     Clothing     60
5         301       Sports     75
6         401      Kitchen     50

In [160]:
tmp = product_purchases.merge(product_info).drop(['product_id', 'quantity', 'price'], axis=1).drop_duplicates()

In [169]:
tmp2 = tmp.merge(tmp, on='user_id', how='outer').rename(columns={'category_x':'category1', 'category_y':'category2'})

In [170]:
tmp2

    user_id    category1    category2
0         1  Electronics  Electronics
1         1  Electronics        Books
2         1  Electronics     Clothing
3         1  Electronics       Sports
4         1        Books  Electronics
..      ...          ...          ...
56        4      Kitchen      Kitchen
57        5        Books        Books
58        5        Books     Clothing
59        5     Clothing        Books
60        5     Clothing     Clothing

[61 rows x 3 columns]

In [172]:
tmp3 = tmp2[tmp2.category1 < tmp2.category2]

In [178]:
res = tmp3.groupby(['category1', 'category2'])['user_id']\
    .nunique().reset_index().rename(columns={'user_id':'customer_count'})

In [181]:
res[res.customer_count >= 3].sort_values(['customer_count', 'category1', 'category2'], ascending=[0,1,1])

     category1    category2  customer_count
0        Books     Clothing               3
1        Books  Electronics               3
4     Clothing  Electronics               3
8  Electronics       Sports               3

In [182]:
data = [[1, 'Alice', None, 12000, 'Executive'], [2, 'Bob', 1, 10000, 'Sales'], [3, 'Charlie', 1, 10000, 'Engineering'], [4, 'David', 2, 7500, 'Sales'], [5, 'Eva', 2, 7500, 'Sales'], [6, 'Frank', 3, 9000, 'Engineering'], [7, 'Grace', 3, 8500, 'Engineering'], [8, 'Hank', 4, 6000, 'Sales'], [9, 'Ivy', 6, 7000, 'Engineering'], [10, 'Judy', 6, 7000, 'Engineering']]
employees = pd.DataFrame(data, columns=["employee_id", "employee_name", "manager_id", "salary", "department"]).astype({"employee_id": "int", "employee_name": "string", "manager_id": "Int64", "salary": "int", "department": "string"})

In [183]:
employees

   employee_id employee_name  manager_id  salary   department
0            1         Alice        <NA>   12000    Executive
1            2           Bob           1   10000        Sales
2            3       Charlie           1   10000  Engineering
3            4         David           2    7500        Sales
4            5           Eva           2    7500        Sales
5            6         Frank           3    9000  Engineering
6            7         Grace           3    8500  Engineering
7            8          Hank           4    6000        Sales
8            9           Ivy           6    7000  Engineering
9           10          Judy           6    7000  Engineering

In [199]:
boss = employees[employees.manager_id.isna()]['employee_id'].values[0]

In [200]:
boss

np.int64(1)

In [202]:
boss in tmp['employee_id']

True

In [206]:
df=tmp
subs = df[df.employee_id == 7]['sub_id'].values

In [275]:
from collections import defaultdict
levels = defaultdict(int)
budgets = defaultdict(int)
team_size = defaultdict(int)

In [276]:
def dfs(emp_id, df, level):
    # print('emp_id: ', emp_id)
    if emp_id not in df.employee_id:
        return 0, 0 # team
    levels[emp_id] = level
    subs = df[df.employee_id == emp_id]
    if len(subs) == 1 and np.isnan(subs['sub_id'].values[0]):
        budgets[emp_id] = subs['salary'].values[0]
        team_size[emp_id] = 0
        return budgets[emp_id], team_size[emp_id] + 1

    for i in range(len(subs)):
        row = subs.iloc[i]
        sub_budget, sub_size = dfs(int(row['sub_id']), df, level+1)
        team_size[emp_id] += sub_size
        budgets[emp_id] += sub_budget
    return budgets[emp_id], team_size[emp_id] + 1

In [277]:
_ = dfs(int(boss), df, 1)

In [278]:
levels

defaultdict(int, {1: 1, 2: 2, 4: 3, 8: 4, 5: 3, 3: 2, 6: 3, 9: 4, 10: 4, 7: 3})

In [279]:
budgets

defaultdict(int,
            {8: np.int64(6000),
             4: np.int64(6000),
             2: np.int64(13500),
             5: np.int64(7500),
             1: np.int64(36000),
             9: np.int64(7000),
             6: np.int64(14000),
             10: np.int64(7000),
             3: np.int64(22500),
             7: np.int64(8500)})

In [280]:
team_size

defaultdict(int, {8: 0, 4: 1, 2: 3, 5: 0, 1: 9, 9: 0, 6: 2, 10: 0, 3: 4, 7: 0})

In [281]:
pd.DataFrame({'level': levels, 
              'team_size': team_size,
              'budget': budgets}).reset_index().rename(columns={'index':'employee_id'})

   employee_id  level  team_size  budget
0            1      1          9   36000
1            2      2          3   13500
2            4      3          1    6000
3            8      4          0    6000
4            5      3          0    7500
5            3      2          4   22500
6            6      3          2   14000
7            9      4          0    7000
8           10      4          0    7000
9            7      3          0    8500

In [282]:
tmp = employees.merge(employees[['employee_id', 'manager_id']], left_on='employee_id', 
                right_on='manager_id', how='left')\
    .rename(columns={'employee_id_x':'employee_id', 'employee_id_y':'sub_id'})\
    .drop(['manager_id_x', 'manager_id_y'], axis=1)

In [274]:
tmp

    employee_id employee_name  salary   department  sub_id
0             1         Alice   12000    Executive     2.0
1             1         Alice   12000    Executive     3.0
2             2           Bob   10000        Sales     4.0
3             2           Bob   10000        Sales     5.0
4             3       Charlie   10000  Engineering     6.0
5             3       Charlie   10000  Engineering     7.0
6             4         David    7500        Sales     8.0
7             5           Eva    7500        Sales     NaN
8             6         Frank    9000  Engineering     9.0
9             6         Frank    9000  Engineering    10.0
10            7         Grace    8500  Engineering     NaN
11            8          Hank    6000        Sales     NaN
12            9           Ivy    7000  Engineering     NaN
13           10          Judy    7000  Engineering     NaN